theme: jekyll-theme-minimal
title: "Sebastian Wang\n(王京)"
description: Software Developer |AI for EDA
logo: /profile.jpg
show_downloads: false

# Social media links (optional)
github_username: SebastianWANG2024
# linkedin_username: your-linkedin
# twitter_username: your-twitter
email: jwangjw@connect.ust.hk